apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.name }}
spec:
  schedule: "0 0 * * 0"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 20
      template:
        spec:
          imagePullSecrets:
            - name: {{ .Values.regCredName }} 
          containers:
          - name: {{ .Values.name }}
            envFrom:
            - configMapRef:
                name: {{ .Values.name }}
            volumeMounts:
              - mountPath: /.aws
                name: {{ .Values.name }}
            securityContext: null
            image: {{ .Values.imageName }}
            imagePullPolicy: Always
            resources:
              limits:
                memory: 500Mi
              requests:
                memory: 500Mi
          restartPolicy: Never
          volumes:
            - name: {{ .Values.name }}
              secret:
                optional: false
                secretName: {{ .Values.name }}
      backoffLimit: 1
