---
# Source: auth/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
    
type: Opaque
stringData:
  credentials: |
    [default]
    aws_access_key_id = {{ .Values.secrets.aws_access_key_id }}
    aws_secret_access_key = {{ .Values.secrets.aws_secret_access_key }}